### ISSUE TITLE
Roadmap - GluonTS Models

### ISSUE THREAD

**Issue by mdancho84** [business-science/modeltime.gluonts#12]
## Core Algorithms

- [x] DeepAR
- [x] N-BEATS

## More GluonTS Forecasting Models
- [ ] DeepFactor
- [x] DeepState (Follow #31)
- [ ] Transformer
- [ ] LSTNet
- [x] GP Forecaster (Follow #29)
- [ ] Seq2Seq Models
- [ ] VAR models

## Torch Implementations (GluonTS 0.8.0)

- [ ] DeepAR Torch (Follow #30)

**Comment by Nicky9529** [comment]
The gluonts.model.deepstate package seems interesting with its mix of state space modeling and RNN.

**Comment by mdancho84** [comment]
@Nicky9529 will take a look at it. We are back on GluonTS improvements. Just added GP Forecaster, which is a nice algorithm.

**Comment by mdancho84** [comment]
@Nicky9529 DeepStateEstimator() is completed.  References:
- Documentation: https://business-science.github.io/modeltime.gluonts/reference/deep_state.html
- GitHub Issue Tracking: #31

**Comment by mdancho84** [comment]
No progress - Not a priority for me at the moment, but if you want you can take a stab at it (I would love the help). Just follow what I did for other models, and create Deep Factor.

**Comment by chenx2018** [comment]
Got you. Yep, I can apply the model using Reticulate + Glonts together to train it. Hopelly we will get it in modetime ecosystem in the near future to make the whole process much easier to implement 😀.
